manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: efogdev
      url-base: https://github.com/efogdev
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: "v0.3.0"
      import: app/west.yml
    - name: zmk-pmw3610-driver
      remote: efogdev
      revision: "c9288fb"
    - name: zmk-pointer-2s-mixer
      remote: efogdev
      revision: "a03ff4a"
    - name: zmk-axis-clamper
      remote: efogdev
      revision: "a416d5b"
    - name: zmk-report-rate-limit
      remote: efogdev
      revision: "7f55412"
    - name: zmk-ec11-ish-driver
      remote: efogdev
      revision: "9cdf4d3"
    - name: zmk-auto-hold
      remote: efogdev
      revision: "4682281"
    - name: zmk-trigger-on-boot
      remote: efogdev
      revision: "c06d9d8"
    - name: zmk-behavior-follower
      remote: efogdev
      revision: "76df19c"
    - name: zmk-keymap-shell
      remote: efogdev
      revision: "86dd63e"
    - name: zmk-acceleration-curves
      remote: efogdev
      revision: "d8b272a"
    - name: zmk-input-processor-rotate-plane
      remote: efogdev
      revision: "bf6d960"
    - name: zmk-runtime-config
      remote: efogdev
      revision: "9727296"
  self:
    path: config
